var teclado = require("prompt-sync")();
console.log("--------------");
console.log("-Calculo media-");
console.log("---------------");
var n1 = parseInt(teclado("Digite o numero N1: "));
var n2 = parseInt(teclado("Digite o numero N2: "));
var n3 = parseInt(teclado("Digite o numero N3: "));
var n4 = parseInt(teclado("Digite o numeoro N4: "));
var n5 = parseInt(teclado("Digite o numero N5: "));
var n6 = parseInt(teclado("Digite o numeoro N6: "));
var n7 = parseInt(teclado("Digite o numero N7: "));
var n8 = parseInt(teclado("Digite o numero N8: "));
var n9 = parseInt(teclado("Digite o numero N9: "));
var n10 = parseInt(teclado("DIgite o numero N10: "));
var media = (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10) / 10;
console.log("A media \u00E9 ".concat(media));
